---
name: Build

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 12 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t aspera-client .
      - name: Test
        run: docker run --rm aspera-client idr0001-graml-sysgro/md5sum.txt /tmp/idr0001/
  upload:
    needs: build
    runs-on: ubuntu-latest
    env:
      name: imagedata/download
    steps:
      - name: Get prefix
        id: getprefix
        run: |
          if [ ! -z ${{ env.name }} ]; then
            echo "::set-output name=prefix::${{ env.name }}:"
          else
            echo "::set-output name=prefix::${{ github.repository }}:"
          fi
      - name: Get other tags
        id: gettags
        uses: jupyterhub/action-major-minor-tag-calculator@v1.1.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          prefix: "${{ steps.getprefix.outputs.prefix }}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: startsWith(github.ref, 'refs/tags')
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          tags: ${{ join(fromJson(steps.gettags.outputs.tags)) }}
          push: ${{ startsWith(github.ref, 'refs/tags') }}
